### ISSUE TITLE
Statement Labeling

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/comments_summarization#2]
You may random pick a feature combination, in other words, you can have 6 articles there. Please manually label the contradiction-value of every pair of statements. If the manual work is too large, you can consider only use 3 4 articles for trial.

**Comment by melvintzw** [comment]
resolved by https://github.com/llmhyy/comments_summarization/commit/78a7e9c53b519cf1d3e4e6de480febd42707c7d4
